server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    platform: postgres
    password: "052230"
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000